### ISSUE TITLE
Get trap, undefined object parameter access

### ISSUE THREAD

**Issue by jabyrd3** [GoogleChrome/proxy-polyfill#16]
```
let service = {
    foo: function...
    bar: function...
}
let EndpointFunction(...){
    return service;
}
var proxyService = new Proxy(service, {
                    get: function (target, propKey, receiver) {
                        if (!(propKey in target)) {
                            return new EndpointFunction(target, propKey, receiver);
                        }
                        return service[propKey];
                    }
                });

ex usage:
proxyService.baz('input').bar('blah');
```
This is for a utility function I wrote for my team to enable chaining syntax without predefining every method in the service; it works perfectly with the native proxy object, but is throwing an undefined error when I try to access an object parameter that doesn't exist. Can the polyfill catch undefined object parameter access *before* throwing a typeerror like the native proxy object can?

thanks!

**Comment by samthor** [comment]
No, that's the main caveat of the proxy. It's not for unrestricted data access, it's only for cases where you know all available keys at runtime, and this is enforced by `Object.seal`. It's not possible using just basic ES5 to do this.

**Comment by jabyrd3** [comment]
I figured as much, just wanted to check again. Shame, this was a much cleaner implementation than what i had before.
