### ISSUE TITLE
this polyfill does not support browsers that implement the full ES5 spec

### ISSUE THREAD

**Issue by dd1994** [GoogleChrome/proxy-polyfill#17]
because it use `let`, https://github.com/GoogleChrome/proxy-polyfill/blob/master/proxy.js it's not ES5 🌚

**Comment by samthor** [comment]
Please see the provided [proxy.min.js](https://github.com/GoogleChrome/proxy-polyfill/blob/master/proxy.min.js).

You're welcome to compile the ES6 source to ES5 using your compiler of choice :)
