### ISSUE TITLE
TypeError: 'set' on proxy: trap returned falsish for property

### ISSUE THREAD

**Issue by AlexanderElias** [GoogleChrome/proxy-polyfill#20]
Hello awesome polly! Got an error not sure if it is me but it only happens when I `use strict;`. I am not adding a new path just editing existing path. If it is a bug lets see if we can fix it. If it is me slap me in the face but tell me what I am doing wrong please.

error: `TypeError: 'set' on proxy: trap returned falsish for property 'port'`

### Example

```JavaScript
'use strict'; // this makes the error throw

function ObserveObject(object, callback) {
    function createProxy(prefix, object) {
        return new Proxy(object, {
            set: function(target, property, value) {
				target[property] = value;
                callback(prefix + property, value);
            },
            get: function(target, property) {
				var value = target[property];
				
                if (isObject(value)) return createProxy(prefix + property + '.', value); 
                else return value; 
            }
        });
    }

    return createProxy('', object);
}

function isObject(value) {
	if (value === null || value === undefined) return false;
	else return value.constructor === Object;
}

var o = {
    hello: 'blue',
    app: {
        env: {
            port: 7777,
            la: 1
        }
    },
    more: 'stuff'
};

var m = ObserveObject (o, function(path, value) {
    console.log(path);
    console.log(value);
});

m.app.env.port = 8888;
console.log(m);
```

**Comment by AlexanderElias** [comment]
Oops...

I think I figured it out. 

Link: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set

"For example, suppose a script does obj.name = "jen", and obj is not a proxy, and has no own property .name, but it has a proxy on its prototype chain. That proxy's set handler will be called, and obj will be passed as the receiver."

Should return true in the set method.

**Comment by samthor** [comment]
That's right.

This actually _isn't_ enforced in the polyfills, since we don't know if you're in strict mode ([see here] for a comment on our thoughts).
The error you're seeing is actually from your browser.

**Comment by ORESoftware** [comment]
I have this same error:

https://stackoverflow.com/questions/46227721/typeerror-with-proxy-class-typeerror-set-on-proxy-trap-returned-truish-for

If I return `false`, I get a `TypeError`, and when I return `true` I get a `TypeError`, I can't win! Help!

**Comment by AlexanderElias** [comment]
Hi @ORESoftware,

I am pretty sure the issue you posted on stackoverflow has nothing to do with Proxy or this pollyfill. But I think the issue has to do with the options you passed to your Object.defineProperty method. Change your `writable` option from `false` to `true` and I think your issue should be resolved.

**Comment by ORESoftware** [comment]
I know I just figured I get a good answer here and I appreciate your input :) I think you're right. But why are you right? I can't figure out why...setting writable to false should allow it be written the first time.

**Comment by AlexanderElias** [comment]
MDN has the following description for the writable property.

> **writable**
true if and only if the value associated with the property may be changed with an assignment operator.
Defaults to false.

So technically `Object.defineProperty` is the first setting of the property. But that's a side note. As we can see from MDN's description `writable` set to `false` disallows us from changing the property via an assignment operator `=` is an example of an assignment operator.

**Comment by ORESoftware** [comment]
yeah I was looking at that thanks

**Comment by mutuadavid93** [comment]
// NOTE: When Intercepting Sets using Proxy, it throws an Error in "use strict" 
// mode, due to polyfills. Babel on it's own can transpile it without an error.
//
// Solution: Inside the set function return true and you good.
// 
// i.e. 
// var yourSetProxy = new Proxy(targetObject, {
//      set : function (target, property, value) {
// 
//           // Your logic here.
// 
//           return true;
//      }
// });

**Comment by mutuadavid93** [comment]
```
// NOTE: When Intercepting Sets using Proxy, it throws an Error in "use strict"
// mode, due to polyfills. Babel on it's own can transpile it without an error.
//
// Solution: Inside the set function return true and you good.
//
// i.e.
// var yourSetProxy = new Proxy(targetObject, {
//     set : function (target, property, value) {
//
//          //    Your logic here.
//
//         return true;
//      }
// });
```

**Comment by Velkan33** [comment]
Hello, I had a different approach  to this one and absolutely work: 
I just change in my html <script src="./file.js" type="module"></script>  to <script src="./file" type="text/javascript"></script>
