### ISSUE TITLE
Object doesn't support property or method with IE11 (at least)

### ISSUE THREAD

**Issue by msieurtoph** [GoogleChrome/proxy-polyfill#22]
Hi,

This piece of code does not work on IE11 (using this polyfill) but works with the official Proxy javascript object.

```javascript
var x = {};
var p = new Proxy(x, {
  get: function(target, method) {
    return function(){
        // I  apply method "method" to another object ...
        return anotherObject[method].apply(this, arguments);
    }
  },
});

p.hello();
```

The polyfill returns "SCRIPT438: Object doesn't support property or method « hello »" where the official Proxy object correctly forwards the call to the "get" trap (with Chrome, FF, ...). 

If I create the hello method within the x object, it works : 
```javascript
// var x = {};
var x = {hello: function(){ return 'initial hello'} };
var p = ...
```

But I would like to avoid to declare all of he methods inside the proxy service.

Could you help me ?
Thx a lot

**Comment by samthor** [comment]
I'm sorry, that's the main restriction of the polyfill. You can't use proxy objects where the list of properties or methods aren't known at creation time.

But if you define `x` to have all the properties of `target` **when the proxy is created**, then this can work.

**Comment by gameboyzone** [comment]
@samthor 

That helps. Thanks!
