### ISSUE TITLE
Issue with running Polyfill in Internet Explorer 11 - Unknown character at line 50

### ISSUE THREAD

**Issue by gameboyzone** [GoogleChrome/proxy-polyfill#24]
The IE console points to line 50 which looks as follows -

`
throw new TypeError(`Cannot perform '${trap}' on a proxy that has been revoked`);
`

**Comment by gameboyzone** [comment]
To resolve this, please change the starting and ending single-quotes in parenthesis to double quotes. See below -

`
throw new TypeError("Cannot perform '${trap}' on a proxy that has been revoked");
`

**Comment by radomeit** [comment]
Hi, same goes for
`throw new TypeError("Proxy polyfill does not support trap '${k}'");`

**Comment by samthor** [comment]
Please use `proxy.min.js` for IE11. It's the compiled ES5 version.
