### ISSUE TITLE
Basic "get" not working

### ISSUE THREAD

**Issue by tslater** [GoogleChrome/proxy-polyfill#31]
I'm trying to get this to work on ReactNative, using version `=0.1.6`. 
Here is the Proxy call: 
```
const example = new Proxy({}, { get: (target, name) => name in target ? target[name] : new Set() });
```

Unfortunately, that doesn't give me a set when I call `example.anyPropertyName`

I'm trying to work through the source code, but It's a bit above me. Any suggestions on how to get through it?

**Comment by samthor** [comment]
From the README:

> This means that the properties you want to proxy **must be known at creation time**.

So this generic proxy won't work.

Out of curiosity, does ReactNative not have a `Proxy` implementation of its own?

**Comment by tslater** [comment]
Ahhh that is why. I get it now. Also, Proxy is not in ReactNative itself, only in the js runtime that is uses from iOS, and only in newer versions. Android and older iOS versions are out of luck.

**Comment by stephan-v** [comment]
What is the use if all properties need to be know beforehand? Doesn't this completely nullify the power of what a fully fledge ES6 proxy is suppose to be capable of?

**Comment by samthor** [comment]
The native `Proxy` is incredibly powerful, yup.

This polyfill can still be useful for say, intercepting calls to a known API surface or change notifications for objects with known keys. We can't do more—there's no other way (aside costly dirty-checking) to approach this for older browsers.

**Comment by stephan-v** [comment]
Guess we will wait for the remains of internet explorer to be put down for good. Thanks.

**Comment by gg4u** [comment]
Older Safari not working either.

proxy.[test] = 'test'
and proxy.test will be undefined..
