### ISSUE TITLE
ES5 version

### ISSUE THREAD

**Issue by qk0106** [GoogleChrome/proxy-polyfill#34]
Why is it not compiled to ES5? 
Safari 9 is complaining "let" key word.
Most of js libs will do es5 as the ultimate result of transpile.
I know dealing with cross browser issue is quite annoying, but can Google be the most professional in the world at least? Feel free to regard this as a complaining letter.

**Comment by samthor** [comment]
Please use `index.min.js`, the included ES5 version.
