### ISSUE TITLE
IE11 recognizes Proxy of an Array as a plain Object, not an Array

### ISSUE THREAD

**Issue by ElliotNB** [GoogleChrome/proxy-polyfill#35]
If you run the following code in Chrome:
```
var foo = [1,2,3];
var bar = new Proxy(foo,{});
console.log(Array.isArray(bar));
console.log(JSON.stringify(bar));
```
then it will log this to the console:
```
true
[1,2,3]
```
However, if you run that same code in IE11 with proxy-polyfill, then it will log this:
```
false
{"0":1,"1":2,"2":3}
```

Is this an issue that can be resolved or is it just an ES5 limitation?

**Comment by ElliotNB** [comment]
After looking more closely at the code, it seems there's no point in fixing this because Arrays can't be proxied with pure ES5.

**Comment by samthor** [comment]
Unfortunately this is impossible as you cannot redefine the "properties" (i.e., 0, 1, 2,.. the indicies) of an array. So we have to pretend it's an `Object`.
