### ISSUE TITLE
Template literals unsupported in IE 11

### ISSUE THREAD

**Issue by wbern** [GoogleChrome/proxy-polyfill#36]
Importing this polyfill requires us to parse it through our `babel-loader` with [babel-plugin-transform-es2015-template-literals](https://babeljs.io/docs/plugins/transform-es2015-template-literals/) enabled.

Could this be fixed?

**Comment by ElliotNB** [comment]
Have you tried using proxy.min.js? It's compiled ES5 version. This was reported in an earlier issue: https://github.com/GoogleChrome/proxy-polyfill/issues/24

**Comment by wbern** [comment]
@ElliotNB Thanks for the quick answer! Since you answered so quickly, maybe you can help me figure out how to import the minified package instead, using webpack? 👍 Understand if it's out of scope.

**Comment by wbern** [comment]
Ok, I solved it by adding a resolve alias to webpack.

```
    alias: {
        "proxy-polyfill": path.resolve(__dirname, "../../node_modules/proxy-polyfill/proxy.min.js"),
    }
```

Alternatively if you want to transpile it, the way I did it in the beginning, add this to the `babel-loader`.

```
            {
                test: /\.js$/,
                exclude: /node_modules(?!(\/|\\)proxy-polyfill)/,
                use: [
                    ...
                ]
            },
```
