### ISSUE TITLE
new Proxy() returns a function, doesn't play well with `react-dom`

### ISSUE THREAD

**Issue by wbern** [GoogleChrome/proxy-polyfill#37]
`react-dom` checks if `window.Proxy` exists and then tries to use it. It also tries to assign properties onto the proxy object, which fails because it's a function in this polyfill.

Can this be fixed?

**Comment by samthor** [comment]
So we `Object.seal(proxy);` before it is returned so you can't add more properties.

Remember that this polyfill only allows _known_ properties to be proxied, no more can be added after creation. The only way a `Proxy` polyfill could allow that is by dirty-checking—other options might do that but it'll be much slower and/or inconsistent.

**Comment by wbern** [comment]
React 16.3 alpha releases now disregard this polyfill by checking if its sealed. Problem solved!
