### ISSUE TITLE
Class properties not proxied

### ISSUE THREAD

**Issue by marvinhagemeister** [GoogleChrome/proxy-polyfill#44]
Been using the proxy-polyfill for a while now and I'm really happy with it. Thanks for making it 🎉 

I've encountered only one issue so far and that is that classes don't seem to be proxied correctly.

Example:

```js
const ProxyFactory = require("proxy-polyfill/src/proxy");
const PProxy = ProxyFactory();

function observe(o, callback) {
  return new Proxy(o, {
    set(target, property, value) {
      callback(property, value);
      target[property] = value;
      return true;
    },
  });
}

class Foo {
  foo = "bar";
}

const f = new Foo();
observe(f, (prop, value) => {
  console.log("prop: " + prop, "value: " + value);
});

f.foo = "foobar";
// observer callback is never executed
```

There don't seem to be any `setters` attached to `Foo.foo`.

**Comment by devshark** [comment]
You have a typo in your code. You declared PProxy but you're initializing Proxy. Anyway, that's not the problem.

I think the problem is how you declare your class properties. You have to declare it in the constructor. 

ProxyPolyfill requires that the properties you want to proxy must be known at creation time.

```js
class Foo {
  constructor(){
    this.foo = "bar";
  }
}
```

**Comment by samthor** [comment]
I wrote a test to check for this (it'll go in soon) before realising you have a bug in your code:

```js
observe(f, (prop, value) => {
  console.log("prop: " + prop, "value: " + value);
});

f.foo = "foobar";
```

You're still setting a property on the original object; you actually want something like:

```js
const p = observe(f, (prop, value) => {
  console.log("prop: " + prop, "value: " + value);
});

p.foo = "foobar";
```
