### ISSUE TITLE
IE11 doesn't support template literals

### ISSUE THREAD

**Issue by kettanaito** [GoogleChrome/proxy-polyfill#45]
When using this on IE11 it throws on one of your error:

```js
throw new TypeError(`Cannot perform '${trap}' on a proxy that has been revoked`);
```

Bundling your library with "production" environment produces the following error:
```
Error: vendor.js from UglifyJs
Unexpected token: name (lastRevokeFn) [vendor.js:57606,6]
```

**Comment by ThiefMaster** [comment]
Can this please be fixed properly? IE11 support is the whole point of using this polyfill - and then you don't transpile to something IE11 can actually use?!

**Comment by kettanaito** [comment]
@ThiefMaster this is not related to the issue I've posted, but it may be useful for you to know that this polyfill is not really efficient. See this part of the README:

> The polyfill supports just a limited number of proxy 'traps'. It also works by calling seal on the object passed to Proxy. This means that the properties you want to proxy must be known at creation time.

This means that it can only proxy Object properties which are *known* at the time proxy is created. For my use case this was a reason to abandon the usage of this polyfill, as it was useless.

Hope that helps.

**Comment by JeremyCraigMartinez** [comment]
@kettanaito Is there another Polyfill you are using now? Or did you abandon using `Proxy` all together?

**Comment by kettanaito** [comment]
@JeremyCraigMartinez @samthor Thankfully, I was in charge of the solution which introduced Proxy at the first place. Thus it wasn't much of an effort to get rid of Proxy entirely in order to support IE.

**Comment by samthor** [comment]
[Fixed](https://github.com/GoogleChrome/proxy-polyfill/commit/7511c4d180079ca7c9a375142dccfd5b427cd312) and released on NPM as 0.3.0.

**Comment by mikhailian** [comment]
Can we resuscitate this issue?

**Comment by ashthornton-gc** [comment]
I ran into the same issue as @wyqydsyq.

Until this is resolved my solution is to include passing the specific node_module through Babel in my webpack config:

```
rules: [
    {
        test: /\.js$/,
        exclude: /node_modules(?!\/proxy-polyfill)/,
        loader: 'babel-loader',
        options: {
            presets: ['es2015']
        }
    }
]
```
