### ISSUE TITLE
Crash on Android with version 0.3.0

### ISSUE THREAD

**Issue by henrikra** [GoogleChrome/proxy-polyfill#50]
I have just added `import 'proxy-polyfill';` on top of my root file in React Native project. And when running it on Android I will get this error

![image](https://user-images.githubusercontent.com/12229968/50446207-73ea9b00-091c-11e9-879b-f29816c29ec8.png)

I guess this is related https://github.com/GoogleChrome/proxy-polyfill/issues/26 but the problem still exists

**Comment by TheHighriser** [comment]
What version do you run? Because I have no problems with React Native.

**Comment by samthor** [comment]
Why do you need the polyfill here?

**Comment by TheHighriser** [comment]
Is the question for me? Or for the thread owner? (Answer for me - React Native doesnt support Proxy?)

**Comment by samthor** [comment]
The [last change](https://github.com/GoogleChrome/proxy-polyfill/blob/master/src/index.js) to the project attempted to work on React Native detection. This has been an issue for a long time—maybe the original author is using an older version of the polyfill.
