### ISSUE TITLE
Usage Proxy as a function example does not clear

### ISSUE THREAD

**Issue by romannep** [GoogleChrome/proxy-polyfill#51]
That's because one should call exported function to get Proxy constructor.

The correct example might look like:
```js
// commonJS require
const ProxyPolyfill = require('proxy-polyfill/src/proxy')();

// Your environment may also support transparent rewriting of commonJS to ES6:
import ProxyPolyfillFunc from 'proxy-polyfill/src/proxy';
const ProxyPolyfill = ProxyPolyfillFunc();

// Then use...
const myProxy = new ProxyPolyfill(...);
```

**Comment by sdyalor** [comment]
If IE11? how to use?

**Comment by romannep** [comment]
example above iis suitable

**Comment by sdyalor** [comment]
Currently I'm using 
```
import 'proxy-polyfill/proxy.min.js';
```
But having some problems with Comlink ;'c
I cant get Comlink to work with IE11

**Comment by devshark** [comment]
Thanks! Saved me half of a day.

**Comment by skesarwani** [comment]
I am getting **Invalid Character**, if importing from src/proxy:

![image](https://user-images.githubusercontent.com/9078001/74863025-32644d00-5373-11ea-8ccf-8ebf93bf6936.png)

![image](https://user-images.githubusercontent.com/9078001/74863209-8111e700-5373-11ea-8ba1-a61164a7b7ae.png)
![image](https://user-images.githubusercontent.com/9078001/74863257-95ee7a80-5373-11ea-8a58-2e81168436ed.png)


and error **Function expected**, if importing from proxy.min.js

![image](https://user-images.githubusercontent.com/9078001/74855376-99c7d000-5366-11ea-8d5f-8272f34f4fc6.png)

![image](https://user-images.githubusercontent.com/9078001/74855445-b82dcb80-5366-11ea-9f8d-39e7e8248278.png)
![image](https://user-images.githubusercontent.com/9078001/74855410-ab10dc80-5366-11ea-9f33-2c935b63cc53.png)

Thanks, any help will be appreciated

**Comment by samthor** [comment]
I've updated the documentation in the README about how to include the code. It wasn't quite right.

The recommended way is just to bring in `proxy.min.js`—don't use anything from that file, just import it directly.
