### ISSUE TITLE
Proxy.revocable, revoke function holds reference to target, can't be garbage collected

### ISSUE THREAD

**Issue by askbeka** [GoogleChrome/proxy-polyfill#54]
Since revoke is used to make proxy unusable, and loosing reference to proxy:
```javascript
const revocable = Proxy.revocable(target, handler);
revocable.revoke();
revocable.proxy = null;
```
should mean that target is free to be garbage collected.

But revoke has a [reference](https://github.com/GoogleChrome/proxy-polyfill/blob/master/src/proxy.js#L43) to target
and needs to be nulled too
```javascript
revocable.revoke = null;
```
I you aware of this behavior? I could not find any reference to correct behavior?

**Comment by samthor** [comment]
Yes, this seems like an issue. Thanks for pointing it out.
