### ISSUE TITLE
How to use it in angular 4 project

### ISSUE THREAD

**Issue by hiwotamare** [GoogleChrome/proxy-polyfill#55]
I am using a library  called "builder-pattern" that uses es6 proxy in my angular 4 project. And I added this javascript file(import "../node_modules/proxy-polyfill/src/index.js") in the polyfill.ts file. But IE 11 still throws an error. Is there any one who used this library in angular 2+ successfully. If so please help?

**Comment by westor21** [comment]
Today I spent some time to make this work.
In the file where I use the proxy I did this:

```
import proxyPolyfillFunc from 'proxy-polyfill/src/proxy';
..
if (window['Proxy']) {
    proxy = new Proxy(o, handler);
} else {
    const ProxyPolyfill = proxyPolyfillFunc();
    proxy = new ProxyPolyfill(o, handler);
}

```
My IE 11 also has a problem with ES 6 template strings, I got an error at lines like this (line 45) in the source of this polyfill:

```
throw new TypeError(`Proxy polyfill does not support trap '${k}'`);

```
I replaced the template strings with normal concatenated strings and it worked.

**Comment by westor21** [comment]
Ah, for the ES6 compatibility I see, I have to import the minified version:
`
import proxyPolyfillFunc from 'proxy-polyfill/proxy.min.js';
`

**Comment by venkateshparihar** [comment]
can you give the polyfills code for it

**Comment by westor21** [comment]
What do you mean? My answer referred the library in this repo. The code remains in node_modules/proxy-polyfill after npm `install proxy-polyfill`

**Comment by venkateshparihar** [comment]
I want to know how you  are Implementing  proxy polyfills in angular

**Comment by venkateshparihar** [comment]
![Capture1](https://user-images.githubusercontent.com/7732063/59691484-ad7fcd00-9200-11e9-9f82-b0e384c8a996.PNG)
![Capture](https://user-images.githubusercontent.com/7732063/59691485-ae186380-9200-11e9-8205-8ef5c0949013.PNG)


comlink is working properly in all browser except ie and vendor js error comes after implementing proxy  polyfills can you send me demo app where you integrate it in angular.

thanks in advance

**Comment by westor21** [comment]
Here is a small Demo. It runs in IE 11 too.
https://stackblitz.com/edit/angular-proxy-polyfill

**Comment by kesarwanishashwat-nagarro** [comment]
I am getting this as function expected in IE11
![image](https://user-images.githubusercontent.com/42133292/74854493-6afd2a00-5365-11ea-9013-d45a881e7621.png)

implemented following:
![image](https://user-images.githubusercontent.com/42133292/74854569-85cf9e80-5365-11ea-84ef-cdb039ff61c9.png)

![image](https://user-images.githubusercontent.com/42133292/74855080-3473df00-5366-11ea-91f0-e6c6ad4c7dc4.png)


Thanks

**Comment by skesarwani** [comment]
I am getting the error as **Function expected**

![image](https://user-images.githubusercontent.com/9078001/74855376-99c7d000-5366-11ea-8d5f-8272f34f4fc6.png)

Implemented following: 

![image](https://user-images.githubusercontent.com/9078001/74855445-b82dcb80-5366-11ea-9f8d-39e7e8248278.png)

![image](https://user-images.githubusercontent.com/9078001/74855410-ab10dc80-5366-11ea-9f33-2c935b63cc53.png)

Thanks, any help is appreciated.

**Comment by samthor** [comment]
I've updated the documentation in the README about how to include the code. It wasn't quite right.

The recommended way is just to bring in `proxy.min.js`—don't use anything from that file, just import it directly.
