### ISSUE TITLE
Exception thrown and not caught 

### ISSUE THREAD

**Issue by abadfish** [GoogleChrome/proxy-polyfill#57]
Environment: Ubuntu 18.04, React 16.6.1.
Problem: Project will not render in IE11. 
Expected behavior: 
Proxy-polyfill takes care of the error:  ```'Proxy' is undefined``` but then throws ```Exception thrown and not caught```
I've tried to trace it and comment out the source but it still persists. I've never tried to debug in IE and I'd love some help if anyone has any tips. This has been a full day of hell so far.

![image](https://user-images.githubusercontent.com/12982176/57026562-218df380-6c08-11e9-9ed4-ab3485033862.png)

**Comment by samthor** [comment]
I'm sorry, I don't know how to debug this (and yes, I know IE is hard to debug). This might not even be coming from our code.

**Comment by binomialstew** [comment]
I'm seeing this also in IE11 and in my case, it's actually coming from: `throw new TypeError("Proxy polyfill does not support trap '"+h+"'")` on line 3 of `proxy.min.js`. And I'm using the minified import as suggested [here](https://github.com/GoogleChrome/proxy-polyfill/issues/24#issuecomment-308116078).

**Comment by samthor** [comment]
We only support four basic traps, as documented: get, set, apply and construct.

If you're seeing that `TypeError` then I suspect you're asking for another trap. There's a [bunch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/Proxy), most of which we don't support.
