### ISSUE TITLE
IE11 doesn't support template literals

### ISSUE THREAD

**Issue by OneCyrus** [GoogleChrome/proxy-polyfill#59]
opening this as #45 is not fixed

**Comment by FerdinandAnt** [comment]
Have you tried this?
(using version 0.3.0)

```
import 'proxy-polyfill/proxy.min';
```

**Comment by drgx** [comment]
The es2015 version

**Comment by ahnpnl** [comment]
hi @FerdinandAnt , I tried to use `import 'proxy-polyfill/proxy.min.js';` but I ran into another error in IE11 that arrow function from comlink source doesn't work for ie11. Do you have a way to workaround it ?
