### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by caridy** [GoogleChrome/proxy-polyfill#6]
How to build the proxy.min.js?

**Comment by samthor** [comment]
It's compiled with Closure compiler - I use [this script](https://gist.github.com/samthor/c45f0de665e9788c6dc6) but I could also update the docs to mention it.

However, I suspect that folks using the script as part of their larger projects would just use `proxy.js` directly and combine it with an existing build process.

**Comment by caridy** [comment]
Sure, but a contributor should try the end to end before submitting a patch, and that should include the build, please, document it in the contributing guidelines.

**Comment by samthor** [comment]
The `CONTRIBUTING.md` file is a stock Google file.

We now have compile instructions at the bottom of `README.md`.
