### ISSUE TITLE
How to support IE?

### ISSUE THREAD

**Issue by JeewhanR** [GoogleChrome/proxy-polyfill#62]
Hello?

I have a problem using this module, so I have a question.

I am creating a Web application with React through TypeScript and using the latest version of the module called [create-react-app](https://github.com/facebook/create-react-app).

I use a library called [immer](https://github.com/immerjs/immer), and I know that this library uses Proxy internally.

---

Thus, I found proxy-polyfill while I am searching online, especially is a problem for IE users with proxy.

I installed and deployed proxy-polyfill because support supports IE9 or higher.

[The polyfill supports browsers that implement the full ES5 spec, such as IE9+ and Safari 6+.](https://github.com/GoogleChrome/proxy-polyfill#supports)

But just because package.json include proxy-polyfill, customers who use IE will not be able to access the website at all.

I re-read README.md because I don't understand the situation well.

In '[To assignment Proxy to the global object](https://github.com/GoogleChrome/proxy-polyfill#to-assign-proxy-to-the-global-object)', the included source is said to be es5 and package.json also confirmed that main is 'proxy.min.js'.

However, in the [Installation](https://github.com/GoogleChrome/proxy-polyfill#installation) section guide, `If you'd like to just get the polyfill' version, use the required status as above`.

I think `polyfill'd version` doesn't need because It written ES5!

Am I wrong? Please let me know. please!

---

I have also added `import "proxy-polyfill/proxy.min"` to src/index.js,
but it is not accessible from IE as it was at the time of installation. [Link](https://github.com/GoogleChrome/proxy-polyfill/issues/24#issuecomment-308116078)

Even though I tried to include `proxy.min.js` in index.html (THE FIRST ENTRY OF APP), but it doesn't works too.

How to support IE?

**Comment by sdyalor** [comment]
Why did u closed this issue ;c
I cant deploy this with comlink, how to support ie11?

**Comment by FelipeCorso** [comment]
I'm facing the same situation.
IE doesn't support proxies.

**Comment by samthor** [comment]
If you just need to support old browsers and you don't have a build system (e.g., you can't `import` code), then you can just include the script directly, e.g.:

```js
<script src="https://unpkg.com/proxy-polyfill"></script>
```

before your other code. It's not the best way to enable `Proxy` support, but it will work.
