### ISSUE TITLE
Proxy polyfill calls get after typecheck error in ie11

### ISSUE THREAD

**Issue by skesarwani** [GoogleChrome/proxy-polyfill#66]
I am creating safe navigation in angular project using Proxy.

I included proxy.min.js in my angular 7 project (in scripts of angular.json).

Now proxy object is no more unknown in IE11, but the get method for dot operator of object is called only if the property is defined.

```
let a = {
         b: {
            d: {
               f: 0
            }
         },
         c: {
            d:10
         },
         g: 'Hello'
      }
```
```
if(a.b.c.d){
  console.log('In if');
} else{
  console.log('In else')
}
```
so i called a.b.c.d where c is not the property of b, so the proxy get handler is called in chrome where i return new object in case of undefined, but this does not work in IE11.

It is expected to land in else part if any property is undefined.

error in IE: 

![image](https://user-images.githubusercontent.com/9078001/75098666-0baa4e80-55df-11ea-9439-85c6a8b7a6be.png)

expected(getting it in crome):
![image](https://user-images.githubusercontent.com/9078001/75098766-3fd23f00-55e0-11ea-8e1f-f07b357f3ae9.png)

**Comment by samthor** [comment]
From the README, sorry:

> The polyfill supports just a limited number of proxy 'traps'. It also works by calling seal on the object passed to `Proxy`. This means that the properties you want to proxy **must be known at creation time.**

This is working as intended. You must define all properties first.
