### ISSUE TITLE
Using `Proxy` across realms

### ISSUE THREAD

**Issue by caridy** [GoogleChrome/proxy-polyfill#7]
The polyfill uses `instanceof` extensibly to detect object and function instances, but this fails when creating proxies for objects from another document. At first glance, it seems that using `typeof` might be enough.

**Comment by samthor** [comment]
I've tried this in #8 - does this work for you?

How common is this problem? I feel like `instanceof` is used fairly universally.

**Comment by caridy** [comment]
@samthor I have reviewed the PR, added few notes. As for `instanceof`, it is known for being problematic, that's why we have decided to provide reliable reflective APIs to mitigate this problem, e.g.: `Array.isArray`.

**Comment by caridy** [comment]
closed by #8
