### ISSUE TITLE
Proxy target objects getting freezed after instantiating proxy.

### ISSUE THREAD

**Issue by dubeyAditya** [GoogleChrome/proxy-polyfill#73]
I am using proxy for custom ui framework.  And somewhere in lifecycle I need to define new properties.
The chrome is supporting to modify my target object but IE freezed it, and throws Cant define property on non-extensible object.

**Comment by samthor** [comment]
> The polyfill supports just a limited number of proxy 'traps'. It also works by calling seal on the object passed to Proxy. This means that the properties you want to proxy must be known at creation time.

Sorry, but this is a limitation of the polyfill.

**Comment by dubeyAditya** [comment]
Thanks @samthor !
